name: CI
on:
  workflow_dispatch:
  push:
    branches:
    - main
    - master
  pull_request:
    branches:
    - main
    - master

jobs:
  unix:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, macos-11, macos-12]
    

    steps:
      - uses: actions/checkout@v2
      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v1

      - name: install mamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: env.yml
          environment-name: xeusqt

      - name: install cxx compiler
        shell: bash -l {0}
        run: |
          $HOME/micromamba-bin/micromamba install cxx-compiler libuuid  -c conda-forge -y

      - name: install xeus-qt
        shell: bash -l {0}
        run: |
          git clone https://github.com/jupyter-xeus/xeus-qt 
          cd xeus-qt
          mkdir -p build
          cd build
          cmake .. \
           -DXEUS_BUILD_TESTS=ON \
           -DCMAKE_PREFIX_PATH=$CONDA_PREFIX \
           -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX 
          make install
          cd ..
          cd ..

      - name: cmake configure
        shell: bash -l {0}
        run: |
          mkdir -p build
          cd build
          cmake .. \
           -DXEUS_BUILD_TESTS=ON \
           -DCMAKE_PREFIX_PATH=$CONDA_PREFIX \
           -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX 

      - name: build
        shell: bash -l {0}
        run: |
          cd build
          make -j 2
          # make -j ${{ steps.cpu-cores.outputs.count }}

     
      - name: install xeus-qt
        shell: bash -l {0}
        run: |
          cd build
          make install

  